<?php

/**
 * Commentaires
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    epharma
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Commentaires
{
	protected $erreur=array(),
			  $_idcommentaires,
			  $_commentaire,
			  $_datecommentaire,
			  $_heritenewsencours,
			  $_auteur;
			  
			  
	const  HERITEMESSAGEENCOURS_INVALIDE=1;
	const  AUTEUR_INVALIDE=2;
			  
	public function __construct($valeur=array())
	{
		if(!empty($valeur))
		{
			$this->hydrate($valeur);
		}
	}
	
	public function hydrate($donnees)
	{
		foreach($donnees as $attribut => $valeur)
		{
			$methode= 'set'.ucfirst($attribut);
			if (is_callable(array($this, $methode)))
			{
				$this->$methode($valeur);
			}
		}
	}
	
	public function isNew()
	{
		return empty($this->_idcommentaires);
	}
	
	public function isValid()
	{
		return !(empty($this->_idcommentaires)||empty($this->_heritenewsencours)||empty($this->_auteur)||empty($this->_commentaire));
	}
	
	
	//LISTE DES SETTERS
	
	public function setIdcommentaires($id)
	{
		$this->_idcommentaire=(int)htmlspecialchars($id);
	}
	
	public function setDatecommentaire($datecommentaire)
	{
		if (is_string($datecommentaire) && preg_match('`le [0-9]{2}/[0-9]{2}/[0-9]{4} à [0-9]{2}h[0-9]{2}`', $datecommentaire))
		{
			$this->_datecommentaire = $datecommentaire;
		}
	}
	
	public function setCommentaire($commentaire)
	{
		if(is_string($commentaire)&&!empty($commentaire))
		{
			$this->_commentaire=(string)htmlspecialchars($commentaire);
			
		}
		else
		{
			$this->erreur[]=self::COMMENTAIRE_INVALIDE;
		}
	}
	
	public function setHeritenewsencours($newsencours)
	{
		$this->_heritenewsencours=(int)htmlspecialchars($newsencours);
	}
	
	public function setAuteur($auteur)
	{
		$this->_auteur=(int)htmlspecialchars($auteur);
	}
	
	//LISTE DES GETTERS 
	
    public function idcommentaires()
	{
		return $this->_idcommentaire;
	}
	
	public function commentaire()
	{
		return $this->_commentaire;
	}
	
	public function datecommentaire()
	{
		return $this->_datecommentaire;
	}
	
	public function heritenewsencours()
	{
		return $this->_heritenewsencours;
	}
	
	public function auteur()
	{
		return $this->_auteur;
	}
	
	public function erreur()
	{
		return $this->_erreur;
	}
		
	
}