<?php

/**
 * Messages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    epharma
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Messages 
{
	protected $erreur=array(),
			  $_idmessages,
			  $_date,
			  $_corps,
			  $_statut,
			  $_emetteur,
			  $_recepteur;
			  
	const  CORPS_INVALIDE=1;
	const  STATUT_INVALIDE=2;
			  
	public function __construct($valeur=array())
	{
		if(!empty($valeur))
		{
			$this->hydrate($valeur);
		}
	}
	
	public function hydrate($donnees)
	{
		foreach($donnees as $attribut => $valeur)
		{
			$methode= 'set'.ucfirst($attribut);
			if (is_callable(array($this, $methode)))
			{
				$this->$methode($valeur);
			}
		}
	}
			  
	public function isNew()
	{
		return empty($this->_idmessages);
	}		  
			  
	public function isValid()
	{
		return !(empty($this->_idmessage)||empty($this->_emetteur)||empty($this->_recepteur));
	}
			  
	
	
	//LISTE DES SETTERS
	
	public function setIdmessages($idmessage)
	{
		$this->_idmessage=(int)$idmessage;
	}
	
	public function setDate($date)
	{
		if (is_string($date) && preg_match('`le [0-9]{2}/[0-9]{2}/[0-9]{4} à [0-9]{2}h[0-9]{2}`', $date))
		{
			$this->_date = $date;
		}	
	}
	
	
	public function setCorps($corps)
	{
		if(is_string($corps)&&!empty($corps))
		{
			$this->_corps=(string)htmlspecialchars($corps);
			
		}
		else
		{
			$this->erreur[]=self::CORPS_INVALIDE;
		}
	}
	
	public function setStatut($statut)
	{
		if(is_string($statut)&&strlen($statut)==1)
		{
			$this->_statut=(string)htmlspecialchars($statut);
		}
		else
		{
			$this->erreur[]=self::STATUT_INVALIDE;
		}
	}
	
	public function setEmetteur($emetteur)
	{
		$this->_emetteur=(int)htmlspecialchars($emetteur);
	}
	
	public function setRecepteur($recepteur)
	{
		$this->_recepteur=(int)htmlspecialchars($recepteur);
	}
	
	//LISTE DES GETTERS
	
	public function idmessages()
	{
		return $this->_idmessage;
	}
	
	public function datem()
	{
		return $this->_date;
	}
	
	public function heure()
	{
		return $this->_heure;
	}
	
	public function corps()
	{
		return $this->_corps;
	}
	
	public function statut()
	{
		return $this->_statut;
	}
	
	public function emetteur()
	{
		return $this->_emetteur;
	}
	
	public function recepteur()
	{
		return $this->_recepteur;
	}
	
	public function erreur()
	{
		return $this->_erreur;
	}
}