<?php

/**
 * Produits
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    epharma
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProduitsManager_PDO extends ProduitsManager
{
	protected $_db;
	
	public function __construct(PDO $db)
	{
		$this->_db=$db;
	}
	
	protected function add(Produits $produits)
	{
		$requete=$this->_db->prepare('INSERT INTO produits SET cip=:cip, code =:code, nom=:nom, categorie=:categorie, existence=\'0\'');
		$requete->BindValue(':cip', $produits->cip());
		$requete->BindValue(':code', $produits->code());
		$requete->BindValue(':nom', $produits->nom());
		$requete->BindValue(':categorie', $produits->categorie());
		$requete->execute();
	}
	
	public function count()
	{
		return $this->_db->query('SELECT COUNT(*) FROM produits ')->fetchColumn();
	}
	
	
	
	public function getList($debut= -1, $limite = -1)
	{
		$listeproduit=array();
		$sql='SELECT idproduits, cip, code, nom, categorie FROM produits WHERE existence=\'0\' ORDER BY idproduits DESC';
		
		if($debut != -1 || $limite != -1)
		{
			$sql .= ' LIMIT '.(int)htmlspecialchars($limite).' OFFSET '.(int)htmlspecialchars($debut);
		}
		$requete=$this->_db->query($sql);
		while($donnees=$requete->fetch(PDO::FETCH_ASSOC))
		{
			$listeproduit[]=new Produits($donnees);
		}
		return $listeproduit;
	}
	
	public function delete($id)
	{
		$requete->_db->prepare('UPDATE produits SET existence\'1\' WHERE idproduits=:id');
		$requete->BindValue(':id', (int)htmlspecialchars($id), PDO::PARAM_INT);
		$requete->execute();
		$requete->closeCursor();
	}
	
	public function getRecentList()
	{
		$produit=array();
		$requete=$this->_db->query('SELECT idproduits, cip, code, nom, categorie FROM produits WHERE existence=\'0\' ORDER BY idproduits DESC LIMIT 0, 3');
		while($donnees=$requete->fetch(PDO::FETCH_ASSOC))
		{
			$produit[]=new Produits($donnees);
		}
		return $produit;
	}
	
	public function getApproximativeList($motcle)
	{
		$produit=array();
		$requete=$this->_db->query('SELECT * FROM produits WHERE nom LIKE \'%'.$motcle.'%\' OR cip LIKE \''.$motcle.'%\' OR code LIKE \''.$motcle.'%\' OR categorie LIKE \''.$motcle.'%\'');
		while($donnees=$requete->fetch(PDO::FETCH_ASSOC))
		{
			$produit[]=new Produits($donnees);
		}
		return $produit;
	}
	
	public function getUnique($id)
	{
		$requete=$this->_db->query('SELECT idproduits, cip, code, nom, categorie FROM produits WHERE existence=\'0\' AND idproduits=:id');
		$requete->BindValue(':id', (int)htmlspecialchars($id), PDO::PARAM_INT);
		$requete->execute();
		$requete->closeCursor();
	}
	
	protected function update(Produits $produits)
	{
		$requete=$this->_db->prepare('UPDATE produits SET cip=:cip, code=:code, nom=:nom, categorie=:categorie WHERE idproduits=:id');
		$requete->bindValue(':cip', $produits->cip());
		$requete->bindValue(':code', $produits->code());
		$requete->bindValue(':nom', $produits->nom());
		$requete->bindValue(':categorie', $produits->categorie());
		$requete->bindValue(':id', $produits->idproduits());
		$requete->execute();
		$requete->closeCursor();
	}
}