<?php

/**
 * Stock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    epharma
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Stock
{
	protected $erreur=array(),
	          $_prix,
			  $_disponibilite,
			  $_codepharmacie,
			  $_heriteproduit;
	
	const  PRIX_INVALIDE=1;
	const  CODEPHARMACIE_INVALIDE=2;
	const  HERITEPRODUIT_INVALIDE=3;
	
	public function __construct($valeur=array())
	{
		if(!empty($valeur))
		{
			$this->hydrate($valeur);
		}
	}
	
	public function hydrate($donnees)
	{
		foreach($donnees as $attribut => $valeur)
		{
			$methode= 'set'.ucfirst($attribut);
			if (is_callable(array($this, $methode)))
			{
				$this->$methode($valeur);
			}
		}
	}
	
	public function isNew()
	{
		return empty($this->_heriteproduit);
	}
	
	public function isValid()
	{
		return !(empty($this->_prix)||empty($this->_disponibilite)||empty($this->_codepharmacie)||empty($this->_heriteproduit));
	}
	
	
	//LISTE DES SETTERS
	
	public function setPrix($prix)
	{
		if(is_float($prix))
		{
			$this->_prix=(double)htmlspecialchars($prix);
		}
		else
		{
			$this->erreur[]=self::PRIX_INVALIDE;
		}
	}
	
	public function setDisponibilite($disponibilite)
	{
		if(is_int($disponibilite)&&strlen($disponibilite)==1)
		{
			$this->_disponibilite=(int)htmlspecialchars($disponibilite);
		}
		else
		{
			$this->erreur[]=self::DISPONIBILITE_INVALIDE;
		}
	}
	
	public function setCodepharmacie($codepharmacie)
	{
		$this->_codepharmacie=(int)htmlspecialchars($codepharmacie);
	}
	
	public function setHeriteproduit($produit)
	{
		$this->_heriteproduit=(int)htmlspecialchars($produit);
	}
	
	//LISTE DES GETTERS
	
	public function prix()
	{
		return $this->_prix;
	}
	
	public function disponibilite()
	{
		return $this->_disponibilite;
	}
	
	public function codepharmacie()
	{
		return $this->_codepharmacie;
	}
	
	public function heriteproduit()
	{
		return $this->_heriteproduit;
	}
	
	public function erreur()
	{
		return $this->_erreur;
	}
}